CREATE DATABASE IF NOT EXISTS demoglpi
CHARACTER SET utf8mb4
COLLATE utf8mb4_unicode_ci;

USE demoglpi;

CREATE TABLE IF NOT EXISTS hook_logs (
    id INT AUTO_INCREMENT PRIMARY KEY,
    fecha DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data LONGTEXT NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
